### ISSUE TITLE
Fix Runbook configuring Wordpress settings

### ISSUE THREAD

**Issue by arbitrarytech** [noop-inc/blueprint-wordpress#1]

**Comment by nathanielks** [comment]
Result of the investigation was two fold: firstly, variables weren't being assigned to the InstallWordPress component because they were all scoped to the WordPress component, and secondly, WP_ENV was missing as an environment variable and the S3 Uploads plugin wasn't using an instance profile for authenticating with AWS.

I've set a reminder for myself to bring up these details on Tuesday. I'm wondering if we should rethink Variables being scoped to components individually.
